// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "enemy_bat":return img`
. . f f f . . . . . . . . f f f 
. f f c c . . . . . . f c b b c 
f f c c . . . . . . f c b b c . 
f c f c . . . . . . f b c c c . 
f f f c c . c c . f c b b c c . 
f f c 3 c c 3 c c f b c b b c . 
f f b 3 b c 3 b c f b c c b c . 
. c 1 b b b 1 b c b b c c c . . 
. c 1 b b b 1 b b c c c c . . . 
c b b b b b b b b b c c . . . . 
c b 1 f f 1 c b b b b f . . . . 
f f 1 f f 1 f b b b b f c . . . 
f f 2 2 2 2 f b b b b f c c . . 
. f 2 2 2 2 b b b b c f . . . . 
. . f b b b b b b c f . . . . . 
. . . f f f f f f f . . . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "myAnim":
            case "anim1":return [img`
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
......fbd1111111f.......
......fdd1111111df......
......fddd111111df......
......fdddddd111df......
......fdddddd111df......
......fbddddddd1df......
......ffbbddbfd1df......
.......fcbbdcfddbf......
.......fffbddccffff.....
.......ffffcfbbb1bcf....
......ffffffffcd1b1f....
....fffffffff..fdfdf....
.....ffffff.....f.f.....
........................
........................
........................
........................
........................
`, img`
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
......fbd1111111f.......
......fdd1111111df......
......fddd111111df......
......fdddddd111df......
......fdddddd111df......
......fbddddddd1df......
......ffbbddbfd1df......
.......fcbbdcfddbf......
.......fffbddcffff......
.......ffffcfbb1bcf.....
......ffffffffd1b1f.....
.....ffffffff.fdfdf.....
......fffff....f.f......
........................
........................
........................
........................
........................
`, img`
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
......fbd1111111f.......
......fdd1111111df......
......fddd111111df......
......fdddddd111df......
......fdddddd111df......
......fbddddddd1df......
......ffbbddbfd1df......
.......fcbbdcfddbf......
.......fffbddcffff......
.......ffffcfbb1bcf.....
.......fffffffd1b1f.....
......fffffff.fdfdf.....
.....ffffff....f.f......
........................
........................
........................
........................
........................
`];
            case "myAnim1":
            case "anim3":return [img`
. . f f f . . . . . . . . f f f 
. f f c c . . . . . . f c b b c 
f f c c . . . . . . f c b b c . 
f c f c . . . . . . f b c c c . 
f f f c c . c c . f c b b c c . 
f f c 3 c c 3 c c f b c b b c . 
f f b 3 b c 3 b c f b c c b c . 
. c 1 b b b 1 b c b b c c c . . 
. c 1 b b b 1 b b c c c c . . . 
c b b b b b b b b b c c . . . . 
c b 1 f f 1 c b b b b f . . . . 
f f 1 f f 1 f b b b b f c . . . 
f f 2 2 2 2 f b b b b f c c . . 
. f 2 2 2 2 b b b b c f . . . . 
. . f b b b b b b c f . . . . . 
. . . f f f f f f f . . . . . . 
`, img`
. . f f f . . . . . . . . . . . 
f f f c c . . . . . . . . f f f 
f f c c c . c c . . . f c b b c 
f f c 3 c c 3 c c f f b b b c . 
f f c 3 b c 3 b c f b b c c c . 
f c b b b b b b c f b c b c c . 
c c 1 b b b 1 b c b b c b b c . 
c b b b b b b b b b c c c b c . 
c b 1 f f 1 c b b c c c c c . . 
c f 1 f f 1 f b b b b f c . . . 
f f f f f f f b b b b f c . . . 
f f 2 2 2 2 f b b b b f c c . . 
. f 2 2 2 2 2 b b b c f . . . . 
. . f 2 2 2 b b b c f . . . . . 
. . . f f f f f f f . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . c c . c c . . . . . . . . 
. . f 3 c c 3 c c c . . . . . . 
. f c 3 b c 3 b c c c . . . . . 
f c b b b b b b b b f f . . . . 
c c 1 b b b 1 b b b f f . . . . 
c b b b b b b b b c f f f . . . 
c b 1 f f 1 c b b f f f f . . . 
f f 1 f f 1 f b c c b b b . . . 
f f f f f f f b f c c c c . . . 
f f 2 2 2 2 f b f b b c c c . . 
. f 2 2 2 2 2 b c c b b c . . . 
. . f 2 2 2 b f f c c b b c . . 
. . . f f f f f f f c c c c c . 
. . . . . . . . . . . . c c c c 
`, img`
. f f f . . . . . . . . f f f . 
f f c . . . . . . . f c b b c . 
f c c . . . . . . f c b b c . . 
c f . . . . . . . f b c c c . . 
c f f . . . . . f f b b c c . . 
f f f c c . c c f b c b b c . . 
f f f c c c c c f b c c b c . . 
. f c 3 c c 3 b c b c c c . . . 
. c b 3 b c 3 b b c c c c . . . 
c c b b b b b b b b c c . . . . 
c 1 1 b b b 1 1 b b b f c . . . 
f b b b b b b b b b b f c c . . 
f b c b b b c b b b b f . . . . 
. f 1 f f f 1 b b b c f . . . . 
. . f b b b b b b c f . . . . . 
. . . f f f f f f f . . . . . . 
`];
            case "myAnim0":
            case "anim2":return [img`
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
......fbd1111111f.......
......fdd1111111df......
......fddd111111df......
......fdddddd111df......
......fdddddd111df......
......fbddddddd1df......
......ffbbddbfd1df......
.......fcbbdcfddbf......
.......fffbddccffff.....
.......ffffcfbbb1bcf....
.......fffffffcd1b1f....
......fffffff..fdfdf....
......fffff.....f.f.....
........................
........................
........................
........................
........................
`, img`
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
......fbd1111111f.......
......fdd1111111df......
......fddd111111df......
......fdddddd111df......
......fdddddd111df......
......fbddddddd1df......
......ffbbddbfd1df......
.......fcbbdcfddbf......
.......fffbddcffff......
.......ffffcfbb1bcf.....
.......fffffffd1b1f.....
......fffffff.fdfdf.....
......fffff....f.f......
........................
........................
........................
........................
........................
`, img`
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
......fbd1111111f.......
......fdd1111111df......
......fddd111111df......
......fdddddd111df......
......fdddddd111df......
......fbddddddd1df......
......ffbbddbfd1df......
.......fcbbdcfddbf......
.......fffbddcffff......
.......ffffcfbb1bcf.....
.......fffffffd1b1f.....
.......ffffff.fdfdf.....
......fffff....f.f......
........................
........................
........................
........................
........................
`];
        }
        return null;
    })

}
// Auto-generated code. Do not edit.
